name: Build OpenWrt APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK package
        run: |
          mkdir -p ${{ github.workspace }}/output

          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -w /work \
            alpine:latest sh -c "

              apk add --no-cache abuild alpine-sdk sudo git && \

              git config --global --add safe.directory /work && \

              adduser -D builder && \
              echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
              addgroup builder abuild && \

              su builder -c 'abuild-keygen -a -n' && \

              cp /home/builder/.abuild/*.rsa.pub /etc/apk/keys/ && \

              chown -R builder:builder /work && \

              su builder -c 'abuild -F -r -d' && \

              cp -r /home/builder/packages/* /work/output/ && \
              chown -R $(id -u):$(id -g) /work
            "

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-zapret
          path: ${{ github.workspace }}/output/**/*.apk
